# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g615v4nA82jfTeFOGqGMRis4tFv3-VLc
"""



"""<center>

#**COLEGIO SIGLO XXI - EL SOCORRO**
#**PRESENTADO A : ING PAOLA ANDRA QUINTERO**
#**PRESENTADO POR : MARÍA CATAINA BALLESTEROS VESGA**
#**GRADO DECIMO**
#**8 SEPTIEMBRE 2022**

#**¿Qué es Python?** 
#Python es un lenguaje de programación de alto nivel que se utiliza para desarrollar aplicaciones de todo tipo. A diferencia de otros lenguajes como Java o .NET, se trata de un lenguaje interpretado, es decir, que no es necesario compilarlo para ejecutar las aplicaciones escritas en Python, sino que se ejecutan directamente por el ordenador utilizando un programa denominado interpretador, por lo que no es necesario “traducirlo” a lenguaje máquina*



#**Recuperado de:** https://www.becas-santander.com/es/blog/python-que-es.html
"""

print("Esto es una suma")
numero_uno= 12
numero_dos= 7
resultado = numero_uno + numero_dos
print(resultado)

print("Esto es una resta")
numero_uno= 25
numero_dos= 10
resultado = numero_uno - numero_dos
print(resultado)

print("Esto es una Multiplicacion")
numero_uno= 9
numero_dos= 2
resultado = numero_uno * numero_dos
print(resultado)

print("Esto es una División")
numero_uno= 40
numero_dos= 6
resultado = numero_uno / numero_dos
print(resultado)

"""#** EJERCICIOS DE TIPOS DATOS SIMPLES*"""

peso = input("¿Cuál es tu peso en kg? ")
estatura = input("¿Cuál es tu estatura en metros?")
imc= round(float(peso)/float(estatura)**2,2)
print("Tu indece de masa muscular es " + str(imc))

"""## Ejercicio 1
Ecribir un programa que pregunte el nombre del usuario en la consola y un número entero e imprima por pantalla las líneas distintas el nombre del usuario tantas veces como el número introducido
"""

nombre = input("¿Cómo te llamas? ")
 n = input("Introduce un número entero: ")
 print((nombre + "\n") * int(n))

"""##Ejercicio 2
Escribir un programa que pida al usuario su peso (en kg) y estatura (en metros), calcule el índice de masa corporal y lo almacene en una variable, e imprima por pantalla la frase 'Tú indice de masa corporal es <imc>' donde '<imc>' es el índice de masa corporal calculado  redondeado  con 2 decimales
"""

peso = input("¿Cúal es tu pesoen Kg? ")
estatura = input("¿Cúal es tu estatura en metros?")
imc = round(float(peso)/float(estatura)**2,2)
print("Ti índice de masa corporal es " + str(imc))

"""# **LIBRERÍAS EN PHYTON**"""